### ISSUE TITLE
Routing issue

### ISSUE THREAD

**Issue by abdullahdd** [smakazmidd/react-starter#3]
Ali,

I am getting an error when I access page 2 directly from browser. I believe this is a routing issue. For your reference I am attaching screenshot of the error.

![image](https://cloud.githubusercontent.com/assets/22519959/20208404/c6aa03aa-a80f-11e6-92ea-50982d56d414.png)

**Comment by smakazmidd** [comment]
thanks abdullah. the sample uses hashHistory and not browserHistory, so the url should be localhost:8080/#/page2.

**Comment by abdullahdd** [comment]
Ok, thanks, got it working by specifying hash. You can close this issue.
